### ISSUE TITLE
Result.php

### ISSUE THREAD

**Issue by zperee** [MastersProjects/Quizmasters2.0#12]
Wenn man direkt im url result.php aufruft dann wird das letzte quiz ausgerwetet mit 0 punkten

**Comment by Phong6698** [comment]
Globale variable welches das quiz beinhaltet am schluss von result.php wieder auf null setzen. Anfang von result.php überprüfen. Wenn es null ist sollte eine fehlermeldung kommen.

**Comment by Phong6698** [comment]
Man könnte das auch für den "Refresh" benutzen.
(also das man nicht nochmals refresh machen kann.

**Comment by zperee** [comment]
dann kann man das quiz jedoch nicht nocheinmal anzeigen weil es nicht mehr existiert. Weiterleitung auf index.php
