### ISSUE TITLE
Get random question

### ISSUE THREAD

**Issue by Phong6698** [MastersProjects/Quizmasters2.0#2]
How to get random question? SQL? PHP? @zperee

**Comment by Phong6698** [comment]
@zperee suscht machsch es so:
$query = "SELECT TOP".$val."insert query here...";

**Comment by zperee** [comment]
gaht au nöd hani scho probiert.

**Comment by Phong6698** [comment]
wtf? warum ned? es isch ja normale string... hesch schomol versuechts debugge was query string bevor es sendet isch?

**Comment by zperee** [comment]
nei machi mal

**Comment by zperee** [comment]
hahaha es staht richtig dine :joy: aber es gaht nöd

**Comment by Phong6698** [comment]
Was gaht genau ned? Also was staht? Und wenn du das im DB Tool inne gisch? 

PS: han gar ned gwusst das mer emoji inne due chan... voll vo fb.. oder github isch zerst gsi xD

**Comment by zperee** [comment]
hans usegfunde 
wenn du $val = '3' machsch gahts nöd aber wenn du $val = ' 3 ' machsch den gahts wegem abstand :joy:

**Comment by Phong6698** [comment]
Ok xD
