### ISSUE TITLE
Zmartl commit und elia push?

### ISSUE THREAD

**Issue by Phong6698** [MastersProjects/Quizmasters2.0#3]
![github](https://cloud.githubusercontent.com/assets/13161221/14178821/a34263a8-f75c-11e5-8fa5-455e11796c3b.PNG)

Was heisst da?
Das heisst, dass de @zmartl-bbc es commited het, aber de @zperee pushed het. Luca het demfall iegentwo de namme im Eclipse immer nonig gänderet :joy:  

I plees ju tu solf de Problem. sank ju

**Comment by zperee** [comment]
hahaha luca du pflock :laughing:
