### ISSUE TITLE
Refresh makes executes in Database

### ISSUE THREAD

**Issue by Phong6698** [MastersProjects/Quizmasters2.0#7]
When refreshing in form result.php it executes insert in db. Because it evaluate and execute insert into the db in form result.php. 
How we gonna fix it?

**Comment by zperee** [comment]
solved in e1b6eca :blush:

**Comment by Phong6698** [comment]
Eifach i de session en boolean setzte wenn mer es neus quiz afang uf false setzte und nach de uswertig uf true. Denn eifach bevor mer id db öpis schriebt luege öb er uf false isch
- @zperee
